subreddit: llmsecurity
max_posts: 3
disclaimer: "*Automated post. Please discuss below.*"

flairs:
  news: News
  research: Research

prompt_template: |
  Summarize the following text into 1–2 clear, concise sentences suitable for a Reddit post,
  highlighting why it’s relevant to large language model (LLM) security:

  {content}
