- name: google-news
  type: news

- name: arxiv-llm-security
  type: research

- name: reddit-llm-search
  type: reddit-search
  query: "llm security"
  time_filter: day
  exclude_subreddits:
    - llmsecurity
  flair: "Discussion"
